name: Security Secret Scan

on:
  pull_request:
    branches: ["dev", "stage", "main"]

permissions:
  contents: read
  pull-requests: write

jobs:
  secret-scanning-review:
    name: Security Secret Scan
    runs-on: ubuntu-24.04

    steps:
      - name: Secret Scanning Review Action
        uses: advanced-security/secret-scanning-review-action@v2
        with:
          token: ${{ secrets.SECRET_SCAN_REVIEW_GITHUB_TOKEN }}
          runtime: python
          fail-on-alert: true
          fail-on-alert-exclude-closed: true
